include $(PROJ_ROOT)/release/customer_tailor/usbcam_default.mk
interface_disp:=disable
#interface_ai:=disable
#interface_ao:=disable
interface_sd:=disable
interface_ipu:=disable
interface_panel:=disable
#interface_ldc:=disable
interface_ldc:=disable
# interface_shadow:=disable
# interface_vdf:=disable
interface_vdisp:=disable
interface_mipitx:=disable
interface_alsa:=disable
mhal_ge:=disable
mhal_hdmitx:=disable
mhal_ge:=disable
#mhal_aio:=disable
mhal_panel:=disable
mhal_disp:=disable
mhal_ldc:=disable
mhal_mipitx:=disable
#misc_ispalgo:=disable
misc_sigma3a:=disable
